
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qijceioeubmccdmissne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpamNlaW9ldWJtY2NkbWlzc25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NjQ2MjEsImV4cCI6MjA1NzA0MDYyMX0.8a_61geHU6blwMIQ092MHB_tOovO0dDFl-Hi9hE2zsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

console.log("Creating Supabase client with URL:", SUPABASE_URL);
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});

// Log connection status
(async () => {
  try {
    console.log("Testing Supabase connection...");
    const { error, count } = await supabase.from('conversations').select('*', { count: 'exact', head: true });
    if (error) {
      console.error('Supabase connection check failed:', error);
    } else {
      console.log('Supabase connection established successfully. Count:', count);
    }
  } catch (err) {
    console.error('Error checking Supabase connection:', err);
  }
})();
